-- =============================================================================
-- 08. SEED DE CIDADES REAIS (planilha BASE DE DADOS - FRETE.xlsx)
-- =============================================================================
-- 223 cidades reais atendidas pela Antares Distribuidora, importadas da
-- planilha oficial. Faixa/custo/pedido mínimo não vêm da planilha de propósito
-- — são sempre recalculados em tempo real a partir de parametros_custo (ver
-- 20260901120600_funcoes_calculo.sql), nunca congelados por cidade.

insert into public.cidades (transportadora_id, regiao_rota, nome, km, dias_coleta, prazo_entrega, prazo_entrega_consolidado)
select t.id, v.regiao_rota, v.nome, v.km, v.dias_coleta, v.prazo_entrega, v.prazo_entrega_consolidado
from (values
  ('Gramado Transportes', 'Região São Raimundo', 'São Raimundo Nonato', 530, 'SEG A SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Caracol', 'Coronel José Dias', 520, 'SEG A SEX', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Caracol', 'Anísio de Abreu', 580, 'SEG - QUA', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Caracol', 'Bonfim do Piauí', 560, 'SEG - QUA', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Caracol', 'Caracol', 600, 'SEG - QUA', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Caracol', 'Várzea Branca', 545, 'SEG - QUA', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Caracol', 'Jurema', 570, 'SEG - QUA', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Caracol', 'Sao Braz do Piauí', 555, 'SEG - QUA', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Caracol', 'Guaribas', 590, 'SEG', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Caracol', 'Dirceu Arcoverde', 575, 'SEX', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Caracol', 'Dom Inocêncio', 610, 'SEX', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Caracol', 'Fartura do Piauí', 595, 'SEX', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Caracol', 'Sao Lourenco do Piaui', 540, 'SEX', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Itaueira', 'Itaueira', 340, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Itaueira', 'Tamboril do Piauí', 520, 'TER', '48h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Canto do Buriti', 'Canto do Buriti', 405, 'SEG A SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Flores', 'Brejo do Piauí', 520, 'SEG - QUI', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Flores', 'Flores do Piauí', 390, 'SEG - QUI', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Flores', 'Pajeu do Piaui', 430, 'SEG - QUI', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Flores', 'Pavussu', 410, 'SEG - QUI', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Flores', 'Rio Grande do Piauí', 460, 'SEG - QUI', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Flores', 'Ribeira do Piauí', 440, 'SEG', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Floriano', 'Floriano', 240, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Floriano', 'Canavieira', 260, 'TER', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Picos', 'Picos', 310, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Picos', 'Aroeiras do Itaim', 360, 'QUI', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Picos', 'São João da Canabrava', 340, 'QUI', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Picos', 'Sao Luis do Piauí', 365, 'QUI', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Santa Cruz do Piauí', 'Bela Vista do Piauí', 375, 'SEG', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Santa Cruz do Piauí', 'Campinas do Piauí', 385, 'SEG', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Santa Cruz do Piauí', 'Floresta do Piauí', 395, 'SEG', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Santa Cruz do Piauí', 'Isaías Coelho', 400, 'SEG', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Santa Cruz do Piauí', 'Itainópolis', 360, 'SEG', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Santa Cruz do Piauí', 'Paquetá', 330, 'SEG', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Santa Cruz do Piauí', 'Santa Cruz do Piauí', 355, 'SEG', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Santa Cruz do Piauí', 'Santo Inacio do Piaui', 410, 'SEG', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Santa Cruz do Piauí', 'Vera Mendes', 420, 'SEG', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Santa Cruz do Piauí', 'Wall Ferraz', 330, 'SEG', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Santa Cruz do Piauí', 'Bocaina', 310, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Santa Cruz do Piauí', 'Santana do Piauí', 320, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Santa Cruz do Piauí', 'Sao Jose do Piaui', 300, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Santa Cruz do Piauí', 'Sussuapara', 305, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Valença', 'Valença do Piauí', 215, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Palmeirais', 'Curralinhos', 90, 'TER - QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Palmeirais', 'Nazária', 30, 'TER - QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Palmeirais', 'Palmeirais', 120, 'TER - QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Simões', 'Geminiano', 315, 'SEG - QUA - SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Simões', 'Jaicós', 370, 'SEG - QUA - SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Simões', 'Alegrete do Piauí', 400, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Simões', 'Belem do Piaui', 405, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Simões', 'Francisco Macedo', 420, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Simões', 'Marcolândia', 430, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Simões', 'Padre Marcos', 415, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Simões', 'Simões', 440, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Simões', 'Curral Novo do Piauí', 450, 'QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Simões', 'Caridade do Piauí', 435, 'QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Simões', 'Caldeirão Grande do Piauí', 420, 'QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Pio Ix', 'Alagoinha do Piauí', 410, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Pio Ix', 'Francisco Santos', 365, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Pio Ix', 'Fronteiras', 430, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Pio Ix', 'Monsenhor Hipólito', 350, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Pio Ix', 'Pio Ix', 445, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Pio Ix', 'Santo Antônio de Lisboa', 330, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Pio Ix', 'Campo Grande do Piauí', 360, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Pio Ix', 'Vila Nova do Piauí', 345, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Pio Ix', 'São Julião', 380, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Paulistana', 'Acauã', 460, 'SEG - QUA - SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Paulistana', 'Jacobina do Piauí', 520, 'SEG - QUA - SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Paulistana', 'Patos do Piauí', 370, 'SEG - QUA - SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Paulistana', 'Paulistana', 500, 'SEG - QUA - SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Paulistana', 'Massape do Piaui', 390, 'SEG', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Paulistana', 'Betania do Piaui', 480, 'QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Inhuma', 'Barro Duro', 130, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Inhuma', 'Dom Expedito Lopes', 300, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Inhuma', 'Elesbao Veloso', 160, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Inhuma', 'Inhuma', 240, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Inhuma', 'Passagem Franca do Piauí', 180, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Inhuma', 'Ipiranga do Piauí', 260, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Paes Landim', 'Nazare do Piaui', 280, 'QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Paes Landim', 'Paes Landim', 400, 'QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Paes Landim', 'São Francisco do Piaui', 205, 'QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Paes Landim', 'São José do Peixe', 430, 'QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Paes Landim', 'Socorro do Piauí', 400, 'QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Paes Landim', 'São Miguel do Fidalgo', 170, 'QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Agricolândia', 90, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Água Branca', 100, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Amarante', 160, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Angical do Piauí', 130, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Demerval Lobão', 40, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Lagoa do Piauí', 35, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Lagoinha do Piauí', 100, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Monsenhor Gil', 60, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Regeneração', 150, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Sao Goncalo do Piaui', 140, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Sao Pedro do Piauí', 110, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Hugo Napoleão', 130, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Jardim do Mulato', 120, 'TER - QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Miguel Leão', 100, 'QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Olho D''agua do Piaui', 110, 'QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Amarante', 'Santo Antônio dos Milagres', 60, 'QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Nova Santa Rita', 'Colonia do Piaui', 300, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Nova Santa Rita', 'Nova Santa Rita', 380, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Lagoa do Barro', 'Campo Alegre do Fidalgo', 370, 'TER', '48 a 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Lagoa do Barro', 'Capitão Gervásio Oliveira', 420, 'TER', '48 a 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Lagoa do Barro', 'Lagoa do Barro do Piauí', 430, 'TER', '48 a 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Lagoa do Barro', 'Queimada Nova', 500, 'TER', '48 a 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Lagoa do Barro', 'São Francisco de Assis do Pi', 350, 'TER', '48 a 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Lagoa do Barro', 'João Costa', 470, 'TER', '48 a 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região São João', 'São João do Piauí', 430, 'SEG A SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Simplicio', 'Simplício Mendes', 380, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Simplicio', 'Conceicao do Caninde', 420, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Oeiras', 'Oeiras', 280, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Oeiras', 'São João da Varjota', 250, 'QUI', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Bom Jesus', 'Bom Jesus', 600, 'SEG A SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Bom Jesus', 'Currais', 640, 'SEG A SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cristino', 'Alvorada do Gurguéia', 650, 'SEG - QUA - SEX', '48h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cristino', 'Colonia do Gurgueia', 620, 'SEG - QUA - SEX', '48h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cristino', 'Cristino Castro', 600, 'SEG - QUA - SEX', '48h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cristino', 'Eliseu Martins', 700, 'SEG - QUA - SEX', '48h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cristino', 'Manoel Emídio', 650, 'SEG - QUA - SEX', '48h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cristino', 'Palmeira do Piauí', 580, 'SEG - SEX', '48h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cristino', 'Santa Luz', 620, 'QUA - SEX', '48h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Uruçuí', 'Urucui', 450, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Uruçuí', 'Benedito Leite - Ma', 600, 'SEG - QUA- SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Baixa Grande do Ribeiro', 'Ribeiro Gonçalves', 560, 'SEG - QUA - SEX', '48h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Baixa Grande do Ribeiro', 'Baixa Grande do Ribeiro', 580, 'SEG - QUA - SEX', '48h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Marcos Parente', 'Landri Sales', 350, 'SEG A SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Marcos Parente', 'Marcos Parente', 420, 'SEG A SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Marcos Parente', 'Jerumenha', 420, 'SEG A SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Marcos Parente', 'Bertolínia', 400, 'SEG - QUA - QUI', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Marcos Parente', 'Sebastião Leal', 500, 'SEG - QUA - QUI', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Marcos Parente', 'Guadalupe', 350, 'SEG - QUA', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Marcos Parente', 'Porto Alegre do Piauí', 450, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Marcos Parente', 'Antonio Almeida', 400, 'TER - SEX', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Boa Hora', 'Boa Hora', 150, 'TER', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Boa Hora', 'Boqueirão do Piauí', 220, 'TER', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Boa Hora', 'Nossa Senhora de Nazaré', 160, 'TER', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Lagoa de São Francisco', 'Lagoa de São Francisco', 230, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cocal', 'Cocal', 280, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cocal', 'Buriti dos Lopes', 300, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cocal', 'Cocal dos Alves', 260, 'SEG - QUA', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cocal', 'Caraubas do Piaui', 240, 'TER - QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cocal', 'Caxingó', 280, 'TER - QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cocal', 'São José do Divino', 220, 'TER - QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cocal', 'Bom Principio do Piaui', 310, 'QUA - SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Piracuruca', 'Piracuruca', 200, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Capitão de Campos', 'Capitão de Campos', 180, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Capitão de Campos', 'Cocal de Telha', 120, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Capitão de Campos', 'Brasileira', 170, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Piripiri', 'Piripiri', 165, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Piripiri', 'São João da Fronteira', 270, 'TER - QUI', '48h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Piripiri', 'Domingos Mourão', 240, 'TER - QUI', '48h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Pedro Ii', 'Pedro Ii', 200, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Pedro Ii', 'Milton Brandão', 260, 'TER', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Luzilândia', 'Esperantina', 180, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Luzilândia', 'Luzilândia', 230, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Luzilândia', 'Morro do Chapeu', 280, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Luzilândia', 'São João do Arraial', 190, 'SEG - QUA', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Luzilândia', 'Joca Marques', 250, 'SEG - QUA', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Luzilândia', 'Madeiro', 240, 'SEG - QUA', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Luzilândia', 'Joaquim Pires', 260, 'TER - QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Luzilândia', 'Murici dos Portelas', 300, 'TER', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Matias Olímpio', 'Campo Largo do Piauí', 200, 'SEG A QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Matias Olímpio', 'Matias Olímpio', 270, 'SEG A QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Matias Olímpio', 'Miguel Alves', 120, 'SEG A QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Matias Olímpio', 'Nossa Sra dos Remédios', 200, 'SEG A QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Matias Olímpio', 'Porto', 190, 'SEG A QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Matias Olímpio', 'União', 65, 'SEG A QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Matias Olímpio', 'Lagoa Alegre', 95, 'TER - QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Barras', 'Barras', 120, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cabeceiras', 'Batalha', 160, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cabeceiras', 'Cabeceiras do Piauí', 95, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Cabeceiras', 'José de Freitas', 50, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'Prata do Piauí', 100, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'São Miguel da Baixa Grande', 120, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'São Felix do Piauí', 150, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'Santa Cruz dos Milagres', 180, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'Aroazes', 210, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'Pimenteiras', 260, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'Lagoa do Sítio', 250, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'Novo Oriente do Píaui', 270, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'Barra D''alcântara', 240, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'Várzea Grande', 230, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'Francinópolis', 160, 'TER', '24 a 48h', 'ATÉ 03 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'Tanque do Piauí', 300, 'TER', '24 a 72h', 'ATÉ 4 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'Santa Rosa do Piauí', 220, 'TER', '24 a 72h', 'ATÉ 4 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'Cajazeiras do Piauí', 200, 'TER', '24 a 72h', 'ATÉ 4 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'Arraial do Piauí', 240, 'TER', '24 a 72h', 'ATÉ 4 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região Aroazes', 'Francisco Ayres', 210, 'TER', '24 a 72h', 'ATÉ 4 DIAS ÚTEIS'),
  ('Gramado Transportes', 'Região São Miguel do Tapuio', 'São Miguel do Tapuio', 230, 'SEG - QUA - SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região São Miguel do Tapuio', 'Assunção do Piauí', 280, 'SEG - QUA', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região São Miguel do Tapuio', 'Buriti dos Montes', 250, 'SEG', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Castelo', 'Castelo do Piauí', 190, 'SEG - QUA - SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Castelo', 'Juazeiro do Piauí', 180, 'SEG - QUA - SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Castelo', 'Sigefredo Pacheco', 170, 'SEG - QUA', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Castelo', 'Jatoba do Piaui', 200, 'QUA', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Alto Longá', 'Alto Longá', 90, 'SEG - QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Alto Longá', 'Beneditinos', 100, 'SEG - QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Alto Longá', 'São João da Serra', 160, 'SEG - QUI', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Alto Longá', 'Novo Santo Antônio', 110, 'SEG', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Alto Longá', 'Pau D''arco do Piauí', 100, 'SEG', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Campo Maior', 'Campo Maior', 85, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Campo Maior', 'Altos', 40, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Gramado Transportes', 'Região Campo Maior', 'Coivaras', 70, 'QUA', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Corrente', 880, 'SEG - QUA - SEX', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Curimatá', 800, 'SEG - QUA - SEX', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Gilbués', 850, 'SEG - QUA - SEX', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Monte Alegre do Piauí', 870, 'SEG - QUA - SEX', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Redencao do Gurgueia', 830, 'SEG - QUA - SEX', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Sao Goncalo do Gurgueia', 780, 'SEG - QUA - SEX', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Parnaguá', 900, 'QUA - SEX', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Avelino Lopes', 920, 'QUA - SEX', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Cristalandia do Piaui', 950, 'SEG', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Júlio Borges', 930, 'SEG', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Sebastião Barros', 910, 'SEG', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Riacho Frio', 940, 'SEG', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Barreiras do Piauí', 890, 'QUA', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Santa Filomena', 820, 'QUA', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Campelo Vip Cargas', 'Região Corrente', 'Morro Cabeca No Tempo', 870, 'SEX', '48 A 72h', 'ATÉ 04 DIAS ÚTEIS'),
  ('Fonseca Transportes', 'Região Parnaíba', 'Parnaíba', 340, 'SEG A SEX', '24h', 'ATÉ 02 DIAS UTEIS'),
  ('Fonseca Transportes', 'Região Parnaíba', 'Luís Correia', 360, 'SEG A SEX', '48h', 'ATÉ 02 DIAS UTEIS'),
  ('Fonseca Transportes', 'Região Parnaíba', 'Ilha Grande', 350, 'QUA E SEX', '48h', 'ATÉ 02 DIAS UTEIS'),
  ('Fonseca Transportes', 'Região Parnaíba', 'Cajueiro da Praia', 380, 'SEX', '48h', 'ATÉ 02 DIAS UTEIS')
) as v(transportadora_nome, regiao_rota, nome, km, dias_coleta, prazo_entrega, prazo_entrega_consolidado)
join public.transportadoras t on t.nome = v.transportadora_nome;
